### ISSUE TITLE
Compiled package cannot be opened normally in Firfox browser

### ISSUE THREAD

**Issue by rooat** [seed-rs/seed-quickstart-webpack#10] opened 2019-12-17 06:37 UTC
TypeError: Response has unsupported MIME type

**Comment by MartinKavik** [comment] 2020-01-02 18:20
Looks like the old browser. Closing.
@rooat Please provide more information, I'll reopen it once we find out the problem is somewhere else.

**Closed by MartinKavik** 2020-01-02 18:20 UTC
